import { useEffect, useState } from "react";
import { Brain, ChevronRight } from "lucide-react";
import { Link } from "react-router-dom";

import { getTopRecommendations } from "../../services/dashboardRecommendationService";

function RecentAIRecommendations() {
  const [recommendations, setRecommendations] = useState([]);

  useEffect(() => {
    loadRecommendations();
  }, []);

  async function loadRecommendations() {
    const data = await getTopRecommendations();
    setRecommendations(data);
  }

  function getBadge(priority) {
    switch (priority) {
      case "Critical":
        return (
          <span className="px-3 py-1 rounded-full text-xs bg-red-100 text-red-700">
            Critical
          </span>
        );

      case "Medium":
        return (
          <span className="px-3 py-1 rounded-full text-xs bg-yellow-100 text-yellow-700">
            Medium
          </span>
        );

      default:
        return (
          <span className="px-3 py-1 rounded-full text-xs bg-green-100 text-green-700">
            Low
          </span>
        );
    }
  }

  return (
    <div className="bg-white rounded-2xl shadow-sm p-6 h-full">

      <div className="flex items-center gap-3 mb-6">
        <Brain className="text-teal-600" size={26} />

        <div>
          <h2 className="text-2xl font-bold">
            Recent AI Recommendations
          </h2>

          <p className="text-slate-500 text-sm">
            Generated by AI Resource Allocation
          </p>
        </div>
      </div>

      <div className="space-y-4">

        {recommendations.map((item) => {

          const recommendation = item.recommendations[0];

          return (
            <div
              key={item.id}
              className="border rounded-xl p-4 hover:bg-slate-50 transition"
            >

              <div className="flex justify-between items-center">

                <h3 className="font-semibold">
                  {item.phcName}
                </h3>

                {getBadge(item.priority)}

              </div>

              <p className="text-slate-600 mt-2 text-sm">
                {recommendation?.key
                  ?.replace(/([A-Z])/g, " $1")
                  .replace(/^./, (c) => c.toUpperCase())}
              </p>

            </div>
          );
        })}

      </div>

      <Link
        to="/resource_allocation"
        className="mt-6 flex items-center justify-end gap-1 text-teal-600 font-semibold hover:text-teal-700"
      >
        View All
        <ChevronRight size={18} />
      </Link>

    </div>
  );
}

export default RecentAIRecommendations;